In [4]:
import numpy as np
# buat matrix X berukuran 2x3 menggunakan numpy
X = np.array([[25, 15, 6], [10, 8,7]])
X

array([[25, 15,  6],
       [10,  8,  7]])

In [5]:
# tampilkan ukuran dari matrix X
X.shape

(2, 3)

In [6]:
# tampilkan seluruh elemen dari kolom pertama dari matrix X
X[:,0]

array([25, 10])

In [7]:
#Tampilkan seluruh elemen dari baris kedua dari matrix X
X[1,:]

array([10,  8,  7])

In [8]:
# ulangi soal nomor 1 menggunakan PyTorch
import torch

x_pt = torch.tensor([[25, 15, 6], [10, 8,7]])
x_pt

tensor([[25, 15,  6],
        [10,  8,  7]])

In [9]:
x_pt.shape

torch.Size([2, 3])

In [11]:
x_pt[:,0]

tensor([25, 10])

In [12]:
x_pt[1,:]

tensor([10,  8,  7])

In [14]:
#Ulangi soal nomor 1 menggunakan tensorflow
import tensorflow as tf

x_tf = tf.Variable([[25, 15, 6], [10, 8,7]])
x_tf

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[25, 15,  6],
       [10,  8,  7]], dtype=int32)>

In [15]:
x_tf.shape

TensorShape([2, 3])

In [16]:
x_tf[:,0]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([25, 10], dtype=int32)>

In [17]:
x_tf[1,:]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10,  8,  7], dtype=int32)>