In [1]:
import numpy as np

In [2]:
#Buat vector x ukuran 3x1
x = np.array([[10],[6],[87]])
x

array([[10],
       [ 6],
       [87]])

In [3]:
#Hitung nilai L2 Norm dari vector x
(10**2 + 6**2 + 87**2)**(1/2)

87.77812939451375

In [4]:
#Buat vector v dengan elemen (3,4)
v = np.array([[25,15,6,10 ],
              [10,6,15,25],
              [25,15,6,10]])
print("Vector v: ",v )
v.shape

Vector v:  [[25 15  6 10]
 [10  6 15 25]
 [25 15  6 10]]


(3, 4)

In [7]:
#Hitung nilai L2 Norm dari vector v
norm = np.linalg.norm(v)
print("nilai L2 norm: ", norm)

nilai L2 norm:  54.38749856354859


In [8]:
# Menghitung unit vector
unit_v = v / norm
print("Unit vector:", unit_v)

Unit vector: [[0.45966446 0.27579867 0.11031947 0.18386578]
 [0.18386578 0.11031947 0.27579867 0.45966446]
 [0.45966446 0.27579867 0.11031947 0.18386578]]


In [10]:
#Hitung panjang unit vector dari vector v
unit_v = np.linalg.norm(unit_v)
print("Panjang unit vektor: ", np.linalg.norm(unit_v))

Panjang unit vektor:  1.0
