In [ ]:
import numpy as np

In [ ]:
#Buat vector x dengan ukuran 3x1
x = np.array([[15], [10], [87]])
x

array([[15],
       [10],
       [87]])

In [ ]:
#Hitung panjang Vector X
len(x)

3

In [ ]:
#Menampilkan ukuran Vector X
x.shape

(3, 1)

In [ ]:
#Menampilkan tipe data Vector X
type(x)

numpy.ndarray

In [ ]:
#Akses elemen pertama dari Vector X
x[0]

array([15])

In [ ]:
#Menampilkan tipe data pertama dari Vector X
type(x[0])

numpy.ndarray

In [ ]:
#Lakukan transpose pada vector X dan simpan pada vector x_t
x_t = x.T
x_t

array([[15, 10, 87]])

In [ ]:
#Menampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [ ]:
#Lakukan transpose pada vector y dan simpan pada variabel y_t
y = np.array([[15], [10], [87]])
y


array([[15],
       [10],
       [87]])

In [ ]:
y_t = y.T
y_t

array([[15, 10, 87]])

In [ ]:
#Menampilkan ukuran dari vector x_t
x_t.shape

(1, 3)

In [29]:
#Tensorflow dan PyTorch
import tensorflow as tf
import torch

In [36]:
#Tensorflow
x_tf = tf.Variable([[6],[10],[87]])
x_tf
tf.transpose(x_tf)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 6, 10, 87]], dtype=int32)>

In [37]:
tf.transpose(x_tf).shape

TensorShape([1, 3])

In [38]:
y_tf = tf.Variable([[6],[10],[87]])
y_tf
tf.transpose(x_tf)

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[ 6, 10, 87]], dtype=int32)>

In [39]:
tf.transpose(x_tf).shape

TensorShape([1, 3])

In [40]:
#PyTorch
x_pt = torch.tensor([[6], [10], [87]])
x_pt_t = x_pt.T
x_pt_t

tensor([[ 6, 10, 87]])

In [41]:
x_pt_t.shape

torch.Size([1, 3])

In [43]:
y_pt = torch.tensor([[6], [10], [87]])
y_pt_t = x_pt.T
y_pt_t

tensor([[ 6, 10, 87]])

In [44]:
x_pt_t.shape

torch.Size([1, 3])